spring.application.name=meizy

# SQL Server
spring.datasource.url=spring.datasource.url=jdbc:sqlserver://meizyDB.mssql.somee.com;databaseName=meizyDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=Meizy_SQLLogin_1
spring.datasource.password=64wle7uoob
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
