# 1. Remova tudo o que tem depois do nome do banco na URL
spring.datasource.url=jdbc:sqlserver://meizyDB.mssql.somee.com;databaseName=meizyDB

# 2. Usuário e senha normais
spring.datasource.username=Meizy_SQLLogin_1
spring.datasource.password=64wle7uoob
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. FORÇAR as propriedades de SSL direto no gerenciador de conexões (Hikari)
spring.datasource.hikari.data-source-properties.encrypt=false
spring.datasource.hikari.data-source-properties.trustServerCertificate=true